### ISSUE TITLE
complied firmware is not updating via SD card

### ISSUE THREAD

**Issue by github051** [makerbase-mks/MKS-Robin#128]
I have complied the marlin2 firmware successfully and i copied the firmware file to sd card and plug into MKS Robin board. But it is not updating. any idea why ?

**Comment by cjsoong** [comment]
@github051 
Change the file name to firmware.bin.

**Comment by 3Dangel** [comment]
Really?
I have never try that.
I have always copied the Robin.bin
Make sure your power cycle with the SD installed.
Sometime it won’t detect SD insertion due to bad FW ( eg not pun assign for
the SD_detect)

**Comment by github051** [comment]
i tried my self. fw is updated but lcd is not displaying anything

**Comment by github051** [comment]
how to change jerk settings with M code ?

i tried with M205 X10 and enter after that again M500 to store vales in EPROM
but this is also not working

can anybody tried in MKS Robin ?

**Comment by github051** [comment]
> i tried my self. fw is updated but lcd is not displaying anything

Finally its working
