### ISSUE TITLE
Sapphire Pro Robin nano white display

### ISSUE THREAD

**Issue by novio8** [makerbase-mks/MKS-Robin#130]
I have Blank white display on my Sapphire PRO. I copied Robin files to an MicroSD Card. I inserted the MicroSd to 3d PRinter, turn ON booting starts but again white Display. Please anyone help getting my Sapphire PRO back. I don't have original Sapphire Pro anyone willing to share.

**Comment by alfrankgit** [comment]
Please close, the solution is in the other thread in which you asked first.
