### ISSUE TITLE
MKS robin marlin compilation error

### ISSUE THREAD

**Issue by github051** [makerbase-mks/MKS-Robin#141]
Can anybody please help me out on this issue ?
I have attached my config files

![Error](https://user-images.githubusercontent.com/38275035/67379658-d812d580-f5a6-11e9-91ba-dc6a4ad47dfa.JPG)

[Configuration.zip](https://github.com/makerbase-mks/MKS-Robin/files/3761510/Configuration.zip)

**Comment by 3Dangel** [comment]
Try to shorten your folders.
Put your Marlin folder @ C:!root and try

**Comment by github051** [comment]
Thanks for reply.
After placing the marlin folder in C: root directory also same issue .

**Comment by TimPut** [comment]
This is an issue with python3 being stricter about distinguishing byte strings and char strings. Here's the diff from my local checkout which fixes it for me:
```
diff --git a/buildroot/share/PlatformIO/scripts/mks_robin_nano.py b/buildroot/share/PlatformIO/scripts/mks_robin_nano.py
index eb8bca9..8b36d23 100644
--- a/buildroot/share/PlatformIO/scripts/mks_robin_nano.py
+++ b/buildroot/share/PlatformIO/scripts/mks_robin_nano.py
@@ -21,7 +21,8 @@ def encrypt(source, target, env):
         while position < length:
             byte = firmware.read(1)
             if position >= 320 and position < 31040:
-                byte = chr(ord(byte) ^ key[position & 31])
+                byte = ord(byte) ^ key[position & 31]
+                byte = byte.to_bytes(1, byteorder='big')
             robin.write(byte)
             position += 1
     finally:
```

**Comment by github051** [comment]
HI TimPut,
Thanks for reply. After modification as per your code it's working. Once again big thanks.:)

**Comment by github051** [comment]
i am able to compile the robin firmware, But after flashing the new firmware LCD screen is showing Complete even after restart. I am trying to connect via usb no communication.

Marlin fw path: https://github.com/makerbase-mks/MKS-Robin/tree/master/MKS%20Robin/firmware/Marlin2.0-MKS-Robin

**Comment by 3Dangel** [comment]
What version of MKS-Robin do you have ?
What version of LCD do you have?
There is a setting to set different version of LCD

**Comment by github051** [comment]
Iam using Mks robin 2.4 board and Mks_robin_tft 2.0 lcd

**Comment by 3Dangel** [comment]
please read through this post

https://github.com/MarlinFirmware/Marlin/issues/9771
cheers

**Comment by github051** [comment]
Finaly i'm able to complie and upload the Marlin fw 2.0 in my Mks robin 2.4.
Now i am testing all usefull options one by one.

Thanks to all.

**Comment by daniyo27** [comment]
@github051 how did you fix this? I am having the same problem with the same board!

**Comment by 3Dangel** [comment]
Pls download from Marlin official branch and use Atom platformio or Vscode
platformio to compile.

**Comment by daniyo27** [comment]
Thank you so much! I was previously using Atom and was presented with multiple compiling errors. VSCode was a breeze to use and my board works now!

**Comment by 3Dangel** [comment]
Glad to hear it is working!!
Cheers
