### ISSUE TITLE
Does any one have Robin2 bootloader ?

### ISSUE THREAD

**Issue by github051** [makerbase-mks/MKS-Robin#142]

**Comment by 3Dangel** [comment]
If you got yourself into deep hole and no exit, you may as well to try this
https://github.com/jmz52/MKS-Robin-Bootloader
Good luck

**Comment by github051** [comment]
[MKS Robin2_bootloader.zip](https://github.com/makerbase-mks/MKS-Robin/files/4597249/MKS.Robin2_bootloader.zip)
Finally, its working

**Comment by github051** [comment]
Finally, its working
[MKS Robin2_bootloader.zip](https://github.com/makerbase-mks/MKS-Robin/files/4597261/MKS.Robin2_bootloader.zip)
