### ISSUE TITLE
MKS-Robin2 Err5

### ISSUE THREAD

**Issue by JanHH2019** [makerbase-mks/MKS-Robin#151]
where can I find a list with the error codes?
I have with my MKS Robin2 when heating the heating bed or the nozzle every now and then the "Err 5", but unfortunately I find nothing.

**Comment by makerbase-mks** [comment]
Robin2 error type

Err1: The thermal bed exceeds the maximum temperature limit. Please check whether the thermal interface is shorted.
Err2: The print head exceeds the maximum temperature limit. Please check whether the thermal interface is shorted.
Err3: The hot bed exceeds the minimum temperature limit. Please check whether the thermal interface is disconnected.
Err4: The print head exceeds the minimum temperature limit. Please check whether the thermal interface is disconnected.
Err5: Nozzle heating fails, if the nozzle does not reach the set temperature difference within the set time, an error is reported; please check the configuration file settings or check whether the power supply is sufficient;
Err6: The heating bed fails to heat. If the heating bed reaches the set temperature difference within the set time, an error is reported; please check the configuration file settings or check whether the power supply is sufficient;
Err7: thermal runaway; when the temperature rises to the target temperature, the current temperature is lower than the target temperature and exceeds the set temperature within the set time, an error is reported; please check whether the thermal sensitivity is normal or whether the PID value is appropriate.
