### ISSUE TITLE
MKS Robin2 with PWC2 and 220DET modules

### ISSUE THREAD

**Issue by MsnSazabi** [makerbase-mks/MKS-Robin#152]
Hello,

I want both auto shut down and power outage func on my Robin2. According to manual, PWC2 and 220DET modules share same plug on board. How to wire them correctly?

**Comment by makerbase-mks** [comment]
Hi! You can refer to it 
![image](https://user-images.githubusercontent.com/12979070/80166178-eb633400-860f-11ea-9aa6-bbfc1f2220bc.png)
![image](https://user-images.githubusercontent.com/12979070/80166251-12ba0100-8610-11ea-8890-401e1fe9ab07.png)

**Comment by MsnSazabi** [comment]
Thanks. So 220DET is not needed in my case?

**Comment by wortex1979** [comment]
can i use  both auto shut down and power outage (powe loss recovery) func on my mks sgen l v2 ?
