### ISSUE TITLE
MKS robin mini (hot stepper motors)

### ISSUE THREAD

**Issue by Malderin** [makerbase-mks/MKS-Robin#156]
The stepper motors are very hot. How can I reduce the current on the drivers? Firmware marlin.

**Comment by makerbase-mks** [comment]
You can change it of pins_MKS_ROBIN_MINI.h
#define DEFAULT_PWM_MOTOR_CURRENT  { 1030, 1030, 1030 } 
You can decrease the value of DEFAULT_PWM_MOTOR_CURRENT, like this:
#define DEFAULT_PWM_MOTOR_CURRENT  { 800, 800, 800} 
good luck for you!
