### ISSUE TITLE
how to confirgure for cartesian printer

### ISSUE THREAD

**Issue by yummyburger** [makerbase-mks/MKS-Robin#16]
how do i setup configure this board, after i flashed the firmware it just go haywire.

I am about to throw this board away, too bad i bought my printer with this in it and all i see everywhere is just delta including in the config file.

Can someone tell me how can i change it?

**Comment by yummyburger** [comment]
most importantly, how can i set my print bed size

**Comment by makerbase-mks** [comment]
If it's an XYZ machine type , the bed size is the value of your the MAX X-axis distance and MAX Y-axis distance.

**Comment by yummyburger** [comment]
what about this , do i fill this in or leave it empty or just delete it?

#Delta parameters
>DELTA_MAX_RADIUS	135					#the radius of Delta annulus
>PRINTER_RADIUS		197					#the distance from machine center to vertical                                                                  top
>DELTA_DIAGONAL_ROD	346.75					#the length of Delta pole
>DELTA_FLOOR_SAFETY_MARGIN_MM	15				#the safe distance of leveling edge

**Comment by makerbase-mks** [comment]
You don't have to worry about it, you just choose the machine type.
Like this:
">DRIVE_SYSTEM 		        0				#machine type"

**Comment by yummyburger** [comment]
thank you. the printer manufacturer didn't give me the full config file so i don't know what needs to be in there. everytime they send me the file either is very short and every single time is different. 

Do i just download the 2.04, change the machine time to 0 and that will be ok and dont have to change the rest unless the motor is going wrong direction?

1 more problem, used to have E0 & E1 in the touch screen, but after recently with all the flashing. now it only shows E1 but my extruder is installed on E0 though, but it still work. Now the touch screen only show E1 and when i  try to print, after 10 minutes , it kept rebooting by itself.

**Comment by yummyburger** [comment]
Here is my confirguration, can help me check please.

#-------------------------------------------------------------
############ Configuration on Machine #######################
#machine type
#0:xyz
#1:corexy(x_motor = x+y, y_motor = x-y),
#2:corexy(x_motor = x+y, y_motor = y-x),
#3:delta

>DRIVE_SYSTEM 		        0				#machine type

#baud rate setting(1:9600;2:57600;3:115200;4:250000)
>cfg_baud_rate:3

>cfg_language_type		3				#language setting(Simplified Chinese: 1,                                                                 Traditional Chinese: 2, English: 3)


>NUM_EXTRUDER 			1				#number of extruder number(1:singal£ª2:dual)
>HAVE_HEATED_BED 		1				#1£∫enable heated bed  ,0£∫disable heated bed
>EXT0_TEMPSENSOR_TYPE 		1				#1:100k thermistor£ª102£∫MAX31855thermocouple
>EXT1_TEMPSENSOR_TYPE 		1				#1:100k thermistor£ª102£∫MAX31855thermocouple
>HEATED_BED_SENSOR_TYPE 	1				#1:100k thermistor£ª

#-------------------------------------------------------------
############ Fuction settings #######################
>INVERT_X_DIR			1				#X motor direction, 1goes opposite direction;
>INVERT_Y_DIR			1				#Y motor direction, 1goes opposite direction;	
>INVERT_Z_DIR			1				#Z motor direction, 1goes opposite direction;	
>EXT0_INVERSE 			0				#E0motor direction, 1goes opposite direction;
>EXT1_INVERSE 			0				#E1motor direction, 1goes opposite direction;

#pause position (-1 is invalid; Z-axis is relative position)
>cfg_XPOS:-1
>cfg_YPOS:-1
>cfg_ZADD:10

>XAXIS_STEPS_PER_MM		80				#X steps per mm 
>YAXIS_STEPS_PER_MM		80				#Y steps per mm 
>ZAXIS_STEPS_PER_MM		1600				#Z steps per mm 
>EXT0_STEPS_PER_MM		94				#E0 steps per mm 
>EXT1_STEPS_PER_MM		94				#E1 steps per mm 

>X_MAX_LENGTH 			200				#the MAX X-axis distance
>Y_MAX_LENGTH 			200				#the MAX Y-axis distance
>Z_MAX_LENGTH 			200				#the MAX Z-axis distance
>X_MIN_POS 			0				#the MIN X-axis distance
>Y_MIN_POS 			0				#the MIN Y-axis distance
>Z_MIN_POS 			0				#the MIN Z-axis distance

>MIN_EXTRUDER_TEMP		150				#Extruder MIN TEMP,play a protective role
>MAX_EXTRUDER_TEMP 		280				#Extruder MAX TEMP,play a protective role
>MAX_HEATED_BED_TEMP 		150				#Heated bed MAX TEMP£¨play a protective role

>HOMING_ORDER			1				#Set direction of endstops when homing;      
>X_HOME_DIR			-1				#Homing direction(-1:MIN£¨1:MAX)
>Y_HOME_DIR			-1				#Homing direction(-1:MIN£¨1:MAX)
>Z_HOME_DIR			-1				#Homing direction(-1:MIN£¨1:MAX)

>HOMING_FEEDRATE_X 		40				#the feedrate when X homes
>HOMING_FEEDRATE_Y 		40				#the feedrate when Y homes
>HOMING_FEEDRATE_Z 		5				#the feedrate when Z homes

# 1 means endstop always-on,0 is always-off
>ENDSTOP_X_MIN_INVERTING 	1				
>ENDSTOP_Y_MIN_INVERTING 	1				
>ENDSTOP_Z_MIN_INVERTING 	1				
>ENDSTOP_X_MAX_INVERTING 	0				
>ENDSTOP_Y_MAX_INVERTING 	0				
>ENDSTOP_Z_MAX_INVERTING 	0				

# 1 for Min/Max endstop enable in hardware,while 0 disable 
>MIN_HARDWARE_ENDSTOP_X 	1				
>MIN_HARDWARE_ENDSTOP_Y 	1				
>MIN_HARDWARE_ENDSTOP_Z 	1				
>MAX_HARDWARE_ENDSTOP_X 	0				
>MAX_HARDWARE_ENDSTOP_Y 	0				
>MAX_HARDWARE_ENDSTOP_Z 	0				

# 1 for Min/Max endstop enable in software,while 0 disable 
>min_software_endstop_x 	0				
>min_software_endstop_y 	0				
>min_software_endstop_z 	0				
>max_software_endstop_x 	1				
>max_software_endstop_y 	1				
>max_software_endstop_z 	1				

>MAX_FEEDRATE_X		200					#the Max feedrate of X moving mm/s
>MAX_FEEDRATE_Y 	200					#the Max feedrate of Y moving mm/s
>MAX_FEEDRATE_Z 	5					#the Max feedrate of Z moving mm/s
>MAX_FEEDRATE_EXT0 	50					#the Max feedrate of E0 moving mm/s
>MAX_FEEDRATE_EXT1 	50					#the Max feedrate of E1 moving mm/s

>MAX_ACCELERATION_UNITS_PER_SQ_SECOND_X 2500			#the Max acculeration of X printing mm/s^2	
>MAX_ACCELERATION_UNITS_PER_SQ_SECOND_Y 2500			#the Max acculeration of Y printing mm/s^2	
>MAX_ACCELERATION_UNITS_PER_SQ_SECOND_Z 250			#the Max acculeration of Z printing mm/s^2
>MAX_ACCELERATION_EXT0 			3000			#the Max acculeration of E0 printing mm/s^2
>MAX_ACCELERATION_EXT1 			3000			#the Max acculeration of E1 printing mm/s^2

>MAX_TRAVEL_ACCELERATION_UNITS_PER_SQ_SECOND_X		2500	#MAX acceleration of X-axis moving mm/s^2	
>MAX_TRAVEL_ACCELERATION_UNITS_PER_SQ_SECOND_Y		2500	#MAX acceleration of Y-axis moving mm/s^2
>MAX_TRAVEL_ACCELERATION_UNITS_PER_SQ_SECOND_Z		250	#MAX acceleration of Z-axis moving mm/s^2

>cfg_insert_det_module		0				#insert power outage module (1:mks                                                                             220det;0:mks pwc)

>cfg_have_ups_device		1				#whether connects UPS(1:yes;0:no)

>cfg_print_over_auto_close	1				#whether auto-off when print finishes(1:on£ª                                                                   0:off)°£

>cfg_filament_det_trigger_level		1			#the level signal of  outage detection                                                                         module (1:high level;0:low level)

>cfg_filament_in_out_step		1			#the length of filament in-out.
>cfg_filament_change_speed		500			#the speed of filament in-out(mm/min)
>cfg_filament_limit_temperature		175			#the lowest temperature of filament in-out

#Leveling mode settings
>cfg_leveling_mode		0                               #1:auto-leveling; 0:manual leveling

#Manual leveling
>cfg_point_number		5				#the point number of manual leveling(3,4,5                                                                     point available)

#the 5 point location of  manual leveling
>cfg_point1:50,50
>cfg_point2:150,50
>cfg_point3:150,150
>cfg_point4:50,150
>cfg_point5:100,100

#Delta parameters
>DELTA_MAX_RADIUS	0					#the radius of Delta annulus
>PRINTER_RADIUS		0					#the distance from machine center to vertical                                                                  top
>DELTA_DIAGONAL_ROD	0					#the length of Delta pole
>DELTA_FLOOR_SAFETY_MARGIN_MM	0				#the safe distance of leveling edge

>END_EFFECTOR_HORIZONTAL_OFFSET 0				#
>CARRIAGE_HORIZONTAL_OFFSET 0				        #
>ROD_RADIUS 0							#

#the setting of auto-leveling command button
>cfg_auto_leveling_cmd:G28;G32 S2;

>FEATURE_Z_PROBE	0					#0:disable leveling£¨1:enable leveling
>BED_LEVELING_METHOD	1					#0:3 points leveling,1:more points                                                                            leveling,2:4 points leveling
>Z_PROBE_HEIGHT		-1					#the height difference between Z-probe and                                                                     nozzle
>Z_PROBE_X1		-90					#coordinateX1 is preset point
>Z_PROBE_Y1		-90					#coordinateY1 is preset point
>Z_PROBE_X2		90					#coordinateX2 is preset point
>Z_PROBE_Y2		-90					#coordinateY2 is preset point
>Z_PROBE_X3		-90					#coordinateX3 is preset point
>Z_PROBE_Y3		90					#coordinateY3 is preset point

>cfg_leveling_z_speed		1500				#the speed of Z moving when manual leveling                                                                 (mm/min)
>cfg_leveling_xy_speed		3000				#the speed of XY moving when manual leveling                                                                 (mm/min)

#Breakpoints continued playing Z-axis error setting
>cfg_breakpoint_z_error:0.2

>BED_LEVELING_GRID_SIZE 5					#leveling interval
>Z_PROBE_SPEED		5					#the speed of Z-probe
>Z_PROBE_XY_SPEED	100					#the speed of XY

>STEPPER_HIGH_DELAY	0					#Pulse hold time setting(unit: us)


#For Inverting Stepper Enable Pins
>X_ENABLE_ON		0
>Y_ENABLE_ON		0
>Z_ENABLE_ON		0
>EXT0_ENABLE_ON		0
>EXT1_ENABLE_ON		0

#Type of heat manager for this extruder.
#- 0 = Simply switch on/off if temperature is reached.
#- 1 = PID Temperature control.
#- 3 = Dead-time control.

>EXT0_HEAT_MANAGER			1			#
>EXT1_HEAT_MANAGER			1			#

#the PID setting of extruder
>EXT0_PID_INTEGRAL_DRIVE_MAX		230			#the Max value of PID integral saturation 
>EXT0_PID_INTEGRAL_DRIVE_MIN		40			#the Min value of PID integral saturation
>EXT0_PID_P		24					#the setting of P value
>EXT0_PID_I		0.88					#the setting of I value
>EXT0_PID_D		80					#the setting of D value

>EXT1_PID_INTEGRAL_DRIVE_MAX		230			#the Max value of PID integral saturation 
>EXT1_PID_INTEGRAL_DRIVE_MIN		40			#the Min value of PID integral saturation
>EXT1_PID_P				24			#the setting of P value
>EXT1_PID_I				0.88			#the setting of I value
>EXT1_PID_D				80			#the setting of D value

#wifi mode(0:sta;1:ap)
>cfg_wifi_mode:1

#wifi name
>cfg_wifi_ap_name:TP-LINK_C944

#wifi password
>cfg_wifi_key_code:makerbase

#0:disable cloud service 1:enable cloud service
>cfg_cloud_enable:1
#cloud service adress
>cfg_wifi_cloud_host:www.baizhongyun.cn
#cloud service port
>cfg_cloud_port:10086

#-------------------------------------------------------------
############ Function customization #######################

#user-defined function1 and 2
>setmenu_func1_display		1				#1:display this button£¨0:no
>setmenu_func2_display		0				#1:1:display this button£¨0:no

#each command must be separated by semicolon ";" 
>setmenu_func1:M84;
>setmenu_func2:G28;
#G32 S2;

>moreitem_pic_cnt		0				#the number of "more" button 

#edit command for 1~7 "More" button
#each command must be separated by semicolon ";"
#each icon command must be less than 200 bytes
>moreitem_button1_cmd:G28 X0;G28 Y0;G28 Z0;

>moreitem_button2_cmd:G28 X0;G28 Y0;G28 Z0;

>moreitem_button3_cmd:G28 X0;G28 Y0;G28 Z0;

>moreitem_button4_cmd:G28 X0;G28 Y0;G28 Z0;

>moreitem_button5_cmd:G28 X0;G28 Y0;G28 Z0;

>moreitem_button6_cmd:G28 X0;G28 Y0;G28 Z0;

>moreitem_button7_cmd:G28 X0;G28 Y0;G28 Z0;

#the number of "more" button in the printing interface
>morefunc_cnt:2

#button1~button6 function settings
>morefunc1_cmd:G28;
>morefunc2_cmd:G28;
>morefunc3_cmd:G28;
>morefunc4_cmd:G28;
>morefunc5_cmd:G28;
>morefunc6_cmd:G28;

#-------------------------------------------------------------
######  Display customization  #######

>cfg_background_color		0x000000			#the color of screen background

>cfg_title_color		0xFFFFFF			#the color of title text

>cfg_state_background_color	0x000000			#the color of temperature,fan,(etc)                                                                  background
            
>cfg_state_text_color		0xFFFFFF			#the color of temprature,fan,(etc) text

>cfg_filename_background_color	0x000000			#the color of file button

>cfg_filename_color		0xFFFFFF			#the color of file text

>cfg_printingstat_word_background_color		0x000000	#the color of background in printing status

>cfg_printingstat_word_color			0xFFFFFF	#the color of text in printing status

>cfg_BUTTON_3D_effects		0				#3D effects setting (disable: 0, enable: 1)

**Comment by valentinoo0** [comment]
Someone can tell me how to deactivate the pid of the heating bed to be able to use a solid state relay.
Thank you
