### ISSUE TITLE
MKS Robin V2 Print bed size 

### ISSUE THREAD

**Issue by ChrisYOLO** [makerbase-mks/MKS-Robin#176]
So i want to add a bigger bed to my 3d printer but i don't know if my board supports it. I have the MKS Robin v2 TFT 3.2 inch screen one. If i am able i want to do around 400x400x280.But if this is not possible whats the maximum i can go ?

**Comment by makerbase-mks** [comment]
Hi! You can set bed size in robin config.txt file, the firmware support change bed size it, do not worry.
