### ISSUE TITLE
MKS Robin Nano Z home direction revesed and not doing well in middle of work!!

### ISSUE THREAD

**Issue by ArMaN2design** [makerbase-mks/MKS-Robin#192]
Hi...
I have robin nano v1.1 whit drv8825 stp drv on it. whit last firmware online extracted working well. when the board was on and every thing was ok suddenly in between two job an issue happened to z direction home command. without restarting or any thing.
when it began moving to home, it move reverse (upward here) for few mm and then stopped! and never go down again!
I changed direction of home in .cfg file to 1 , it work well in its new direction. when put it to -1 again ,issue was there again.
I change firmware many times, Even install marlin but issue was there, just like first time. changed stepper drive, try to control the board whit pronterface. but changed any thing/

can anyone help me fix this issue pleas?

**Comment by 3Dangel** [comment]
Most likely your Z home sensor got stuck

**Comment by mks-viva** [comment]
@ArMaN2design 
Hi! You can refer to 3Dangel's idea and check Z sensor. But I hope you can provide a video for me.

**Comment by ArMaN2design** [comment]
thanks very much. the problem was exactly from z endstop. the wire was broken from end of one pin. it s work fine now. thanks :)

**Comment by mks-viva** [comment]
This is good news, then I will temporarily close this issue.
