### ISSUE TITLE
Autoleveling for Cartesian printer (Prusa i3 clone)

### ISSUE THREAD

**Issue by 3Dangel** [makerbase-mks/MKS-Robin#2]
Dear MKS,
I am trying to set the autoleveling using MKS-Robin V1.0 board.
I'm not able to set the probe nor can make it to work ...

I think the enabled section of Autoleveling is for the Delta printers.

Would it be possible to  
- allow to set 
 "> ZHOME_X_POS       xxx"
 "> ZHOME_Y_POS       xxx"
 "> Z_PROBE_X_OFFSET xx"
 "> Z_PROBE_Y_OFFSET xx"

Also, to know how the probe should be installed/connect to the Robin board?
Is there any pin out on the board  that it should be used specially for the Z probe beside from the Z-min-endstop?
My printer is Cartesian xyz (Prusa i3 clone, the most popular one)

Thanks in advance...

Robert

**Comment by makerbase-mks** [comment]
yes,it is the Z-min-endstop.
