### ISSUE TITLE
Print though usb fail

### ISSUE THREAD

**Issue by pirogeth** [makerbase-mks/MKS-Robin#20]
Hello, I use S3D for software. I have the driver installed and the config file set up to my printer. Auto Level with sno4-n probe doesnt work right. i wanted the 3x3 grid. and 3/4 of the way through the print it started over again.  I'll attach the config file maybe someone can help.

Thanks in advanced

[robin_config.txt](https://github.com/makerbase-mks/MKS-Robin/files/1350666/robin_config.txt)

**Comment by makerbase-mks** [comment]
You can try replacing a u_disk.
