### ISSUE TITLE
Mks Robin 2.4 bootloader 

### ISSUE THREAD

**Issue by ChrisYOLO** [makerbase-mks/MKS-Robin#201]
So i tried flashing a klipper firmware and someone told me to install another bootloader "https://github.com/jmz52/MKS-Robin-Bootloader", now my printer wont boot to anything, stay at complete screen and flash a blue light. Any idea on how to fix this and how to boot to klipper using my robin.bin file?

**Comment by mks-viva** [comment]
You only select bootloader offset is 28K
