### ISSUE TITLE
USB Driver

### ISSUE THREAD

**Issue by Sensemaya** [makerbase-mks/MKS-Robin#3]
Hello have the mks-Robin v 2 firmware
need the USB driver to connect Repetier host
MKS Aliexpress Costumer service advice to download the **CH340G** usb driver, after install you can see the serial port asigned to the board usb conection but host software can not controll the board Pronterface or Repetier host.
The board works with no conection to computer but need to calibrate board
Thanks

**Comment by 3Dangel** [comment]
Did you change baudrate in pc com port?

**Comment by Sensemaya** [comment]
Hello Thanks for the reply
yes I did see the snapshot
The driver at github can not be installed by the installer in the zip file
make an error.
I install the driver looking by the device manager then pointing to the
file.
Nothing works I use Repetier Host to connect.
and will show is conected but unable to control the board, if the driver is
ok then the board is not working properly,
One of the problems that I see is than MKS do not provide with a Manual or
pinout of their product.
Thnsks to look for a solution.

Carlos
