### ISSUE TITLE
Board broken

### ISSUE THREAD

**Issue by pirogeth** [makerbase-mks/MKS-Robin#34]
During use my screen flipped and went backwards. its off skewed as well. Reflashing the firmware only caused the machine to brick. How can i fix this?

**Comment by makerbase-mks** [comment]
Maybe you should contact our sales representative for replacement

**Comment by pirogeth** [comment]
I have. They told me to reflash it. I told them it doesn't work and what can we do next. They haven't responded since. I'd like to have a replacement.

**Comment by makerbase-mks** [comment]
what's version of your tft32 firmware and hardware.

**Comment by janeyam** [comment]
我也遭遇一样的问题，但是更换sd卡之后就可以完成固件更新，所以跟主板无关，是sd卡质量太差。

**Comment by janeyam** [comment]
I also encountered the same problem, but after the replacement of the sd card can complete the firmware update, so nothing to do with the motherboard, sd card quality is too bad. translation software! !
