### ISSUE TITLE
STM32 Firmware 2.07

### ISSUE THREAD

**Issue by utjfgh** [makerbase-mks/MKS-Robin#40]
Hi, i have an Board STM 32 with Firmware 2.07 then i Installed my Pics and Config file but after Flash the Screen is white i can flash what i want it is White.Were i decome the new 2.07 firmwar for the V2.4 Board STM32.

**Comment by Danijele** [comment]
hello,
now new firmware is downloadeble here!
Try

**Comment by makerbase-mks** [comment]
@utjfgh You can try changing the SD card
@Danijele We have updated the file

**Comment by Danijele** [comment]
Hello Makerbase, temperature manual adjusting with touch is not working, at least when increasing with touch softkey the down tempreature figure disaperes. Adjusting temp within Slicer or rather g Code Works Great. Please Check ans Let ne known! 

Best regards Danijel
