### ISSUE TITLE
Delta Printer with mechanical Probe

### ISSUE THREAD

**Issue by Danijele** [makerbase-mks/MKS-Robin#42]
Hello together,
I bought the Anycubic Kossel Plus Delta printer and after the Trigorilla was broken I Bought the MKS Robin V2.4.
So far everything seems to be o.k. excluding Auto bed Leveling is not working at all.
I connected the Z-Probe (it's ad on with mechanical Endstop) to -Z Enstop conection!
Problem is: When I'm performing leveling the machine goes down and when touching the hot bed the 
the whole Head rattles over the hotbed top. Even when I'm triggering the probe nothing works.
I setet up the Zero in the Center of Hotbed, means wwhen mooving down the nozzle stops 1/10 of a mm before the hotbed. I setetup the paramete: "Z_PROBE_HEIGHT	-15.8".
My problem is that the Probe after touching did not rises up, goes to next probing coordinate and plunges down for next triggering......May somebody help me or rather send mey maybe the config file form Delta with working Autoleveling?!?

Thank you in advance!
Danijel

**Comment by Danijele** [comment]
Hello togehter,
problem solved....If you need help just ask! So far MKS Robin is working propper with my Delta Printer!
Danijel.Timic@gmx.de

**Comment by 3Dangel** [comment]
What was your solution?
Thanks for sharing !!
Robert

**Comment by 3Dangel** [comment]
Thanks for the info.
Cheers
Ribert
