### ISSUE TITLE
mks robin v2.3 & corexy

### ISSUE THREAD

**Issue by rigimod** [makerbase-mks/MKS-Robin#46]
Hello
I made a corexy machine with mks robin v2.3 card, but I am having problems installing the software. axes work like cartesian. what do I need to do step by step? thank you
![img_6060](https://user-images.githubusercontent.com/19257577/41499710-7111400e-718d-11e8-9169-9fbb527bdeb2.JPG)
![img_6070](https://user-images.githubusercontent.com/19257577/41499711-713a4d5a-718d-11e8-87e3-7e69d23f376b.JPG)
![img_6095](https://user-images.githubusercontent.com/19257577/41499712-715e335a-718d-11e8-8f37-11846ffd2a16.JPG)

**Comment by 3Dangel** [comment]
Rig mod,

You would need to go into the config.txt and change the machine type.
And play around.

There will be very little support from China.

Good luck.
Bob

**Comment by makerbase-mks** [comment]
You can configure your machine by following the information in the configuration file.
