### ISSUE TITLE
Possibility to invert Enable for stepper

### ISSUE THREAD

**Issue by 0Jmaster0** [makerbase-mks/MKS-Robin#73]
Hello
I bought 1/256 stepper controllers ST820 which are pin to pin compatible with conrtollers like a4988, drv8825 etc. But they have one difference - their enable pin is reversed in comparison to a4988. Can you add possibility to change behavior of enable pins to be reversed? 

Thank you for answer

**Comment by 3Dangel** [comment]
Do the hardware jump
Will be quicker
Waiting for reply will frustrate you.

Cheers

**Comment by makerbase-mks** [comment]
In the firmware of 2.0.7, there is this configuration item in the configuration file.

#For Inverting Stepper Enable Pins
>X_ENABLE_ON		0
>Y_ENABLE_ON		0
>Z_ENABLE_ON		0
>EXT0_ENABLE_ON		0
>EXT1_ENABLE_ON		0

**Comment by 0Jmaster0** [comment]
Thank you! Didn't notice that in config :)
